name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
    tags:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1

      - name: Run Ci
        run: deno task -q ci
