name: list

on:
  workflow_dispatch:
    inputs:
      origin:
        type: string
        description: Origin
        required: true
      destination:
        type: string
        description: Destination
        required: true
        default: dist

concurrency: ci-${{ github.ref }}

jobs:
  list:
    name: list
    runs-on: ubuntu-latest

    env:
      LIST_ORIGIN: ${{ github.event.inputs.origin}}
      LIST_DESTINATION: ${{ github.event.inputs.destination}}

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1

      - name: Run List
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          deno task list $LIST_ORIGIN $LIST_DESTINATION

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{github.run_id}}.json
          path: ${{ env.LIST_DESTINATION }}
