name: list

on:
  workflow_dispatch:
    inputs:
      origin:
        type: string
        description: Origin
        required: true
      destination:
        type: string
        description: Destination
        required: true
        default: dist

concurrency: ci-${{ github.ref }}

jobs:
  list:
    name: list
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1

      - name: Mask
        run: |
          echo "::add-mask::${{ github.event.inputs.origin}}"
          echo "::add-mask::${{ github.event.inputs.destination}}"

      - name: Run List
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          deno task list ${{ github.event.inputs.origin}} ${{ github.event.inputs.destination}}

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{github.run_id}}.json
          path: ${{ github.event.inputs.destination}}
